import React, { useState } from "react";
import FormField from "../components/FormField";
import Loader from "../components/Loader";
import Card from "../components/Card";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0)
    return data.map((post) => <Card key={post._id} {...post} />);
  return (
    <h2 className="text-[#6449ff] mt-5 text-bold text-xl uppercase">{title}</h2>
  );
};
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPost, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");
  return (
    <section className=" max-w-7xl mx-auto ">
      <div>
        <h1 className="font-extrabold text-black text-[32px]">
          The Community Show Case
        </h1>
        <p className="mt-1 pl-2 text-neutral-500 text-[16px] max-w-[500px]">
          Browse through the stunning images generated by AI{" "}
        </p>
      </div>
      <div className="mt-16">
        <FormField />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-neutral-500 text-xl mb-3">
                Showing Result For{" "}
                <span className="text-black">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 md:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3 ">
              {searchText ? (
                <RenderCards data={[]} title={"No search results found"} />
              ) : (
                <RenderCards data={[]} title="No posts are found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
